import fs from "node:fs";
import fsp from "node:fs/promises";
import path from "node:path";
import { Readable } from "node:stream";
import { env } from "./env";

/**
 * Object storage abstraction. Development uses the local disk; production points at Cloudflare R2
 * (or any S3-compatible bucket). PostgreSQL only ever stores metadata + the storage key.
 * Keys are always generated by the server — never derived from user-supplied filenames.
 */
export interface StoredObject {
  body: ReadableStream<Uint8Array> | Buffer;
  contentType: string;
  size: number;
  /** Set when a byte range was requested. */
  range?: { start: number; end: number; total: number };
}

export interface StorageDriver {
  name: "local" | "s3";
  put(key: string, body: Buffer, contentType: string): Promise<void>;
  get(key: string, range?: { start: number; end?: number }): Promise<StoredObject | null>;
  delete(key: string): Promise<void>;
  /** Public, cacheable URL for objects in a public bucket (S3 driver with S3_PUBLIC_BASE_URL). */
  publicUrl(key: string): string | null;
  /** Short-lived URL for private objects. Local driver returns null (served through the app). */
  signedUrl(key: string, ttlSec?: number): Promise<string | null>;
  /** Direct browser upload (large videos) — S3 only. */
  presignPut?(key: string, contentType: string, ttlSec?: number): Promise<{ url: string; headers: Record<string, string> }>;
}

const MIME_BY_EXT: Record<string, string> = {
  webp: "image/webp", jpg: "image/jpeg", jpeg: "image/jpeg", png: "image/png", gif: "image/gif",
  mp4: "video/mp4", mov: "video/quicktime", webm: "video/webm", mp3: "audio/mpeg", m4a: "audio/mp4",
  wav: "audio/wav", ogg: "audio/ogg", aac: "audio/aac", json: "application/json",
};
export const mimeFromKey = (key: string) => MIME_BY_EXT[key.split(".").pop()?.toLowerCase() ?? ""] ?? "application/octet-stream";

// ── local disk ─────────────────────────────────────────────────────────────
function localRoot() {
  return path.resolve(/*turbopackIgnore: true*/ process.env.STORAGE_LOCAL_DIR || path.join(process.cwd(), "storage"));
}

function safeLocalPath(key: string): string {
  // Keys are server-generated, but defend anyway against traversal.
  if (!/^[a-zA-Z0-9/_\-.]+$/.test(key) || key.includes("..")) throw new Error("Invalid storage key");
  const full = path.resolve(localRoot(), key);
  if (!full.startsWith(localRoot() + path.sep)) throw new Error("Invalid storage key");
  return full;
}

const localDriver: StorageDriver = {
  name: "local",
  async put(key, body) {
    const file = safeLocalPath(key);
    await fsp.mkdir(/*turbopackIgnore: true*/ path.dirname(file), { recursive: true });
    await fsp.writeFile(/*turbopackIgnore: true*/ file, body);
  },
  async get(key, range) {
    const file = safeLocalPath(key);
    let stat: fs.Stats;
    try {
      stat = await fsp.stat(/*turbopackIgnore: true*/ file);
    } catch {
      return null;
    }
    const contentType = mimeFromKey(key);
    if (range) {
      const end = Math.min(range.end ?? stat.size - 1, stat.size - 1);
      const stream = Readable.toWeb(fs.createReadStream(/*turbopackIgnore: true*/ file, { start: range.start, end })) as unknown as ReadableStream<Uint8Array>;
      return { body: stream, contentType, size: end - range.start + 1, range: { start: range.start, end, total: stat.size } };
    }
    return { body: await fsp.readFile(/*turbopackIgnore: true*/ file), contentType, size: stat.size };
  },
  async delete(key) {
    await fsp.rm(/*turbopackIgnore: true*/ safeLocalPath(key), { force: true });
  },
  publicUrl: () => null,
  signedUrl: async () => null,
};

// ── S3 / Cloudflare R2 ─────────────────────────────────────────────────────
function makeS3Driver(): StorageDriver {
  let clientPromise: Promise<import("@aws-sdk/client-s3").S3Client> | null = null;
  const client = () =>
    (clientPromise ??= import("@aws-sdk/client-s3").then(
      ({ S3Client }) =>
        new S3Client({
          region: env.s3.region,
          endpoint: env.s3.endpoint || undefined,
          credentials: { accessKeyId: env.s3.accessKeyId, secretAccessKey: env.s3.secretAccessKey },
          forcePathStyle: !!env.s3.endpoint,
        }),
    ));
  return {
    name: "s3",
    async put(key, body, contentType) {
      const { PutObjectCommand } = await import("@aws-sdk/client-s3");
      await (await client()).send(new PutObjectCommand({ Bucket: env.s3.bucket, Key: key, Body: body, ContentType: contentType, CacheControl: "public, max-age=31536000, immutable" }));
    },
    async get(key, range) {
      const { GetObjectCommand } = await import("@aws-sdk/client-s3");
      try {
        const res = await (await client()).send(
          new GetObjectCommand({ Bucket: env.s3.bucket, Key: key, Range: range ? `bytes=${range.start}-${range.end ?? ""}` : undefined }),
        );
        const bytes = res.Body ? await res.Body.transformToByteArray() : new Uint8Array();
        const total = Number(res.ContentRange?.split("/")[1] ?? bytes.length);
        return {
          body: Buffer.from(bytes),
          contentType: res.ContentType ?? mimeFromKey(key),
          size: bytes.length,
          range: range ? { start: range.start, end: range.start + bytes.length - 1, total } : undefined,
        };
      } catch {
        return null;
      }
    },
    async delete(key) {
      const { DeleteObjectCommand } = await import("@aws-sdk/client-s3");
      await (await client()).send(new DeleteObjectCommand({ Bucket: env.s3.bucket, Key: key }));
    },
    publicUrl: (key) => (env.s3.publicBaseUrl ? `${env.s3.publicBaseUrl}/${key}` : null),
    async signedUrl(key, ttlSec = 600) {
      const [{ GetObjectCommand }, { getSignedUrl }] = await Promise.all([import("@aws-sdk/client-s3"), import("@aws-sdk/s3-request-presigner")]);
      return getSignedUrl(await client(), new GetObjectCommand({ Bucket: env.s3.bucket, Key: key }), { expiresIn: ttlSec });
    },
    async presignPut(key, contentType, ttlSec = 600) {
      const [{ PutObjectCommand }, { getSignedUrl }] = await Promise.all([import("@aws-sdk/client-s3"), import("@aws-sdk/s3-request-presigner")]);
      const url = await getSignedUrl(await client(), new PutObjectCommand({ Bucket: env.s3.bucket, Key: key, ContentType: contentType }), { expiresIn: ttlSec });
      return { url, headers: { "Content-Type": contentType } };
    },
  };
}

let cached: StorageDriver | null = null;
export function storage(): StorageDriver {
  if (!cached) cached = env.storageDriver === "s3" ? makeS3Driver() : localDriver;
  return cached;
}
