import type { ShowcaseCfg } from "./showcase";

/** Anna & Joseph — a Syrian Christian church wedding in Kochi. English only. */
export const CHRISTIAN: ShowcaseCfg = {
  slug: "anna-and-joseph",
  title: "Anna & Joseph",
  date: "2027-02-06",
  template: "chapel-romance",
  theme: "ivory-chapel",
  track: "Ave Verum (ambient)",
  eventType: "christian_wedding",
  journey: { style: "western", headZoom: { bride: 1.9, groom: 2.9 } },
  images: { couple: "hero", ceremony: "ceremony", story: "story" },
  bride: { name: "Anna", fullName: "Anna Mathew", parents: "Daughter of Mr. Thomas & Mrs. Lissy Mathew, Kochi", bio: "A paediatric nurse with a laugh you can hear across a ward and a habit of sketching strangers’ hands on prescription pads. She believes most things are better after a long walk and a hot cup of tea.", photo: "bride" },
  groom: { name: "Joseph", fullName: "Joseph Philip", parents: "Son of Mr. Philip & Mrs. Annie Joseph, Kottayam", bio: "A marine engineer who knows every harbour on the coast and forgets his own wedding anniversary dates on purpose, so that every year feels like a surprise. He sings in the church choir, slightly off-key and entirely sincere.", photo: "groom" },
  tagline: "Two hearts. One quiet promise.",
  invitation: "Together with their families",
  quote: { text: "Love is patient, love is kind. It always protects, always trusts, always hopes, always perseveres.", author: "1 Corinthians 13" },
  hashtag: "AnnaAndJoseph",
  monogram: "AJ",
  venues: [
    { key: "church", name: "St. Mary’s Forane Church", address: "Church Road, Fort Kochi, Kochi, Kerala 682001", city: "Kochi", lat: 9.9658, lng: 76.2421, mapUrl: "https://www.google.com/maps/search/?api=1&query=Fort+Kochi+church", photo: "venue", airport: "Cochin International Airport (COK) is 45 km away, about 1 hour 15 minutes by car.", railway: "Ernakulam Junction is 12 km away, about 35 minutes.", road: "Follow signs for Fort Kochi; the church is on Church Road, opposite the parish hall.", parking: "Parking is available at the parish hall ground, a two-minute walk from the church." },
    { key: "hall", name: "Seaview Grand Ballroom", address: "Marine Drive, Ernakulam, Kochi, Kerala 682031", city: "Kochi", lat: 9.9816, lng: 76.2755, mapUrl: "https://www.google.com/maps/search/?api=1&query=Marine+Drive+Kochi", road: "On Marine Drive, beside the walkway. Valet parking at the main entrance.", parking: "Valet parking is complimentary." },
  ],
  events: [
    { name: "Betrothal", date: "2027-01-31", start: "11:30", end: "14:00", venue: "church", description: "The two families gather after Sunday Mass for the blessing of the rings and a lunch of appam, stew and too many desserts.", dress: "Smart traditional — pastels", colors: ["#F4E7D6", "#BFD0BE", "#E9C9C0"], photo: "betrothal" },
    { name: "The Wedding Mass", date: "2027-02-06", start: "10:30", end: "12:30", venue: "church", description: "The church service, the exchange of vows and the blessing of the marriage. Please be seated by 10:00.", dress: "Formal — ivory, sage, navy", colors: ["#F8F5EF", "#5F7561", "#34404F"], photo: "ceremony", main: true },
    { name: "Reception", date: "2027-02-06", start: "18:30", end: "22:30", venue: "hall", description: "Dinner, toasts and dancing above the bay. The band starts at 8, and so, we promise, does the dessert.", dress: "Evening formal", colors: ["#222B33", "#B79A68", "#F2EEE6"], photo: "reception" },
  ],
  family: { brideName: "The Mathew family", groomName: "The Philip family", members: [["bride", "Mr. Thomas Mathew", "Father of the bride"], ["bride", "Mrs. Lissy Mathew", "Mother of the bride"], ["bride", "Ancy", "Sister of the bride"], ["groom", "Mr. Philip Joseph", "Father of the groom"], ["groom", "Mrs. Annie Joseph", "Mother of the groom"], ["groom", "Jerin", "Brother of the groom"]] },
  intro: "Two hearts.\nOne quiet promise.\nA lifetime of Sundays.\nAnd now, forever.",
  milestones: [
    ["2020", "A hello at the harbour", "A rain-delayed ferry, a shared umbrella, and a conversation that outlasted the weather.", "m1"],
    ["2022", "Sundays", "Mass, then breakfast, then a long walk — every week, whichever city they were in.", "m2"],
    ["2025", "The question", "On the church steps where they first prayed together. He asked; she had already said yes.", "m3"],
    ["2027", "Our wedding", "6 February, with the people who prayed for this day.", "m4"],
  ],
  ceremoniesIntro: "A Syrian Christian wedding is a celebration of faith and family. A short guide to the days, so everyone can follow along.",
  ceremonies: [
    ["Betrothal", "31 January, after Mass", "The families gather to bless the couple’s promise to marry. The rings are blessed by the priest and a small celebration follows.", "rings", "betrothal"],
    ["The church service", "6 February, 10:30 am", "The Holy Mass with readings, a homily and the blessing of the marriage, led by the family’s parish priest.", "lamp", "service"],
    ["Exchange of vows", "6 February, 11:15 am", "Anna and Joseph make their promises to each other before God and the congregation.", "knot", "vows"],
    ["Blessing of the rings", "6 February, 11:30 am", "The rings are blessed and placed on each other’s hands as a sign of faithful love.", "rings", "rings"],
    ["Petals & procession", "6 February, 12:15 pm", "As the couple step out, family and friends shower them with petals and the bells ring.", "flower", "petals"],
    ["Reception", "6 February, 6:30 pm", "Dinner, toasts and dancing by the sea.", "bowl", "reception"],
  ],
  rsvp: { deadline: "2027-01-15", pickups: ["Cochin International Airport (COK)", "Ernakulam Junction"] },
  whatsapp: "919876501000",
  contacts: [["Ancy (wedding coordinator)", "Travel, stay and anything on the day", "+91 98765 01001"], ["Jerin", "Music and the reception", "+91 98765 01002"]],
  palette: { colors: [["#F8F5EF", "Ivory"], ["#5F7561", "Sage"], ["#B79A68", "Champagne gold"], ["#34404F", "Navy"]], note: "Soft ivory and sage for the church; evening formal for the reception." },
  dressAvoid: "White for guests, please — it is the bride’s colour.",
  opening: { variant: "seal", sealText: "AJ", invited: "You are invited to the wedding of" },
  thankYou: { message: "From the bottom of our hearts — thank you for praying, travelling, dancing and making our day complete.\n\nWith love and gratitude,", signature: "Anna & Joseph", photo: "hero" },
  seo: { title: "Anna & Joseph — Wedding Invitation", description: "Together with our families, we invite you to celebrate our wedding on 6 February 2027 in Kochi.", og: "hero" },
  needs: [
    ["hero", "Iv3yJpmOmZc", "COUPLE", { focal: { x: 47, y: 45 } }],
    ["bride", "c9gbbHY_8RU", "BRIDE", { focal: { x: 49, y: 46 } }],
    ["groom", "Iv3yJpmOmZc", "GROOM", { focal: { x: 57, y: 43 } }],
    ["ceremony", "SrWVeL5DyNM", "EVENT"],
    ["story", "KiU1Du5pONA", "COUPLE", { focal: { x: 80, y: 50 } }],
    ["venue", "zyguVcuzeGM", "VENUE"],
    ["betrothal", "9ceNKX2ZlT0", "EVENT"],
    ["service", "coWejNeBFhE", "EVENT"],
    ["vows", "ozOQglKbMuE", "EVENT"],
    ["rings", "RJDWzHyh6gE", "EVENT"],
    ["petals", "6bFp65WVrL8", "EVENT"],
    ["reception", "pyd736FSNvk", "EVENT"],
    ["m1", "6pUz0KMMCX4", "COUPLE"],
    ["m2", "fPFoUSKZGts", "COUPLE"],
    ["m3", "YeJWDWeIZho", "COUPLE"],
    ["m4", "nKJzYDP10Zw", "COUPLE"],
  ],
  gallery: [
    ["6bFp65WVrL8", "Showered with petals"], ["7enPZgey7vE", "The aisle, waiting"], ["q9GlHcaaSn4", "Walking towards the bells"], ["G5a1RNy55pw", "Light through the glass"],
    ["fPFoUSKZGts", "On her father’s arm"], ["ozOQglKbMuE", "Before the priest"], ["GAFpZ63GEYs", "Hand in hand"], ["QPL_171Kf5Q", "Our parish church"],
    ["YyvpmN6PB3I", "The long walk"], ["ouh94xUqOHk", "Under a Kerala sky"], ["h-Q955luWLI", "Ivory, cream, white"], ["KiU1Du5pONA", "A kiss by the old wall"],
  ],
};
