import type { ShowcaseCfg } from "./showcase";

/** Zainab & Imran — a nikah in Hyderabad. English only. */
export const MUSLIM: ShowcaseCfg = {
  slug: "zainab-and-imran",
  title: "Zainab & Imran",
  date: "2027-03-13",
  template: "nikah-noor",
  theme: "emerald-ivory",
  track: "Noor (ambient)",
  eventType: "muslim_wedding",
  journey: { style: "classic", headZoom: { bride: 1.4, groom: 1.2 } },
  images: { couple: "hero", coupleWide: "heroWide", ceremony: "ceremony", story: "story" },
  bride: { name: "Zainab", fullName: "Zainab Siddiqui", parents: "Daughter of Mr. Farooq & Mrs. Nasreen Siddiqui, Hyderabad", bio: "An architect who restores old havelis and keeps a notebook of every doorway she has ever loved. She believes in long dinners, short prayers said on time, and second helpings of haleem.", photo: "bride" },
  groom: { name: "Imran", fullName: "Imran Qureshi", parents: "Son of Mr. Anwar & Mrs. Shaheen Qureshi, Hyderabad", bio: "A paediatric doctor who is always late for dinner and never late for a patient. He plays the harmonium for his nieces, makes a biryani that has started family arguments, and proposed with a letter.", photo: "groom" },
  tagline: "In the name of Allah, the Most Gracious, the Most Merciful.",
  invitation: "Together with their families",
  quote: { text: "And among His signs is that He created for you mates from among yourselves, that you may find tranquillity in them, and He placed between you love and mercy.", author: "Surah Ar-Rum 30:21" },
  hashtag: "ZainabAndImran",
  monogram: "ZI",
  venues: [
    { key: "hall", name: "Noor Mahal Banquet", address: "Road No. 12, Banjara Hills, Hyderabad, Telangana 500034", city: "Hyderabad", lat: 17.4126, lng: 78.4482, mapUrl: "https://www.google.com/maps/search/?api=1&query=Banjara+Hills+Hyderabad", photo: "venue", airport: "Rajiv Gandhi International Airport (HYD) is 32 km away, about 55 minutes by car.", railway: "Secunderabad Junction is 9 km away, about 30 minutes.", road: "On Road No. 12; the entrance is opposite the park. Ample parking on site.", parking: "Valet parking at the main gate; the ladies’ entrance is at the rear." },
  ],
  events: [
    { name: "Mehendi", date: "2027-03-11", start: "17:00", end: "21:00", venue: "hall", description: "An evening of henna, qawwali and sweets with the women of both families. Dinner follows.", dress: "Greens and yellows", colors: ["#2F7D62", "#E8C547", "#F8F4E8"], photo: "mehendi" },
    { name: "The Nikah", date: "2027-03-13", start: "16:30", end: "18:30", venue: "hall", description: "The khutbah, the ijab-o-qubool and the signing of the nikahnama before family and witnesses, followed by dua. Please be seated by 16:15.", dress: "Modest, festive — emerald, ivory, gold", colors: ["#12523F", "#F6EFDD", "#C9A24B"], photo: "ceremony", main: true },
    { name: "Walima", date: "2027-03-14", start: "19:30", end: "23:00", venue: "hall", description: "The groom’s family hosts a feast to celebrate the marriage: dum biryani, shahi tukda, and a great many speeches.", dress: "Evening formal", colors: ["#1F2A44", "#C9A24B", "#8A2432"], photo: "walima" },
  ],
  family: { brideName: "The Siddiqui family", groomName: "The Qureshi family", members: [["bride", "Mr. Farooq Siddiqui", "Father of the bride"], ["bride", "Mrs. Nasreen Siddiqui", "Mother of the bride"], ["bride", "Hina", "Sister of the bride"], ["groom", "Mr. Anwar Qureshi", "Father of the groom"], ["groom", "Mrs. Shaheen Qureshi", "Mother of the groom"], ["groom", "Faisal", "Brother of the groom"]] },
  intro: "Two paths.\nOne letter.\nA hundred late-night phone calls.\nAnd now, forever.",
  milestones: [
    ["2021", "An introduction", "Two families, one cup of chai too many, and an awkward silence that ended in laughter.", "m1"],
    ["2023", "The letter", "He wrote it by hand because he did not trust himself to say it out loud.", "m2"],
    ["2026", "Mangni", "The rings, the families, the sweets — and the first time their mothers cried together.", "m3"],
    ["2027", "The nikah", "13 March, in the presence of the people who prayed for this day.", "m4"],
  ],
  ceremoniesIntro: "A short guide to the days of the wedding, written for friends who are new to our traditions — and for the elders who will correct it.",
  ceremonies: [
    ["Mehendi", "11 March, evening", "Henna for the bride and the women of both families, with songs, sweets and a great deal of laughter.", "flower", "mehendi"],
    ["Mangni", "Already celebrated", "The families formally celebrated the engagement months ago, exchanging gifts and blessings.", "rings", "mangni"],
    ["Nikah", "13 March, 4:30 pm", "The marriage contract: the khutbah, the consent of the bride and groom (ijab-o-qubool) and the signing of the nikahnama, witnessed by family. The nikah closes with dua.", "lamp", "nikah"],
    ["Rukhsati", "13 March, after the nikah", "The bride’s tearful, joyful farewell as she leaves her parents’ home with her husband and their blessings.", "knot", "rukhsati"],
    ["Walima", "14 March, 7:30 pm", "A feast hosted by the groom’s family to celebrate the marriage with everyone who came.", "bowl", "walima"],
  ],
  rsvp: { deadline: "2027-02-20", pickups: ["Rajiv Gandhi International Airport (HYD)", "Secunderabad Junction"] },
  whatsapp: "919876502000",
  contacts: [["Hina (wedding coordinator)", "Travel, stay and anything on the day", "+91 98765 02001"], ["Faisal", "Music and the walima", "+91 98765 02002"]],
  palette: { colors: [["#12523F", "Emerald"], ["#C9A24B", "Gold"], ["#F6EFDD", "Ivory"], ["#E9B7A0", "Blush"]], note: "Emerald and gold for the nikah; evening formal for the walima." },
  dressAvoid: "Please dress modestly for the nikah; the ladies’ and gentlemen’s seating are arranged separately.",
  opening: { variant: "curtain", sealText: "ZI", invited: "You are invited to the nikah of" },
  thankYou: { message: "Jazakum Allahu khairan for travelling, praying with us and making our day complete.\n\nWith love and gratitude,", signature: "Zainab & Imran", photo: "hero" },
  seo: { title: "Zainab & Imran — Nikah Invitation", description: "With the blessings of Allah, we invite you to celebrate our nikah on 13 March 2027 in Hyderabad.", og: "heroWide" },
  needs: [
    ["hero", "1iuFKizvxQo", "COUPLE", { focal: { x: 50, y: 32 } }],
    ["heroWide", "l6BafhpDlZM", "COUPLE", { focal: { x: 50, y: 40 } }],
    ["bride", "21NahBnXWxI", "BRIDE", { focal: { x: 50, y: 22 } }],
    ["groom", "_fb7LvFNJ4k", "GROOM", { focal: { x: 34, y: 22 } }],
    ["ceremony", "ryOiannoQ3g", "EVENT"],
    ["story", "464ps_nOflw", "COUPLE"],
    ["venue", "t8zrGJlSb0M", "VENUE"],
    ["mehendi", "gfVofr15ICc", "EVENT"],
    ["mangni", "jt2iZ0ARWoY", "EVENT"],
    ["nikah", "ryOiannoQ3g", "EVENT"],
    ["rukhsati", "EcERopBq9dg", "EVENT"],
    ["walima", "kdYjB1fsyqw", "EVENT"],
    ["m1", "cRyUjYf6VBQ", "COUPLE"],
    ["m2", "9Lq0zlOu_dw", "COUPLE"],
    ["m3", "jt2iZ0ARWoY", "COUPLE"],
    ["m4", "1iuFKizvxQo", "COUPLE"],
  ],
  gallery: [
    ["464ps_nOflw", "Hand in hand"], ["9Lq0zlOu_dw", "Newlyweds"], ["_G7UyLmY1tc", "Jasmine and lace"], ["EcERopBq9dg", "A blessing, a bow"],
    ["XYwHswmjjVs", "A quiet prayer"], ["-4xe-LfXbDs", "Red, gold and a held breath"], ["AGcM0IujgBU", "Henna hands"], ["_tWvgxrO14M", "Sunset in beads"],
    ["Lk4Au3jIqcY", "Under the chandeliers"], ["mb-qgRDcz-s", "Behind the veil"], ["cRyUjYf6VBQ", "Back to back"], ["2uWUf5K-INY", "In the flowers"],
    ["IiGkUvXXbig", "Joy"], ["t8zrGJlSb0M", "The old doorway"], ["JY0El1DESkw", "Stitched with love"], ["A--OZVONuGE", "Gold on gold"],
  ],
};
