/** Writes docs/FEATURES.md from the live feature catalogue so the docs can never drift from the code. */
import { writeFileSync, mkdirSync } from "node:fs";
import { FEATURES, PACKAGE_KEYS, defaultFeaturesFor } from "../src/domain/packages/features";

const groups = new Map<string, [string, (typeof FEATURES)[keyof typeof FEATURES]][]>();
for (const [k, f] of Object.entries(FEATURES)) groups.set(f.group, [...(groups.get(f.group) ?? []), [k, f]]);
const sets = Object.fromEntries(PACKAGE_KEYS.map((p) => [p, new Set<string>(defaultFeaturesFor(p))]));

let md = `# Feature catalogue\n\n_Generated by \`npm run docs:features\` from \`src/domain/packages/features.ts\`. Package columns show the **default** entitlements; Super Admin can change any of them in **Studio → Packages**, and override a single wedding from its settings._\n\n`;
for (const [g, items] of groups) {
  md += `## ${g}\n\n| Feature | Key | What it does | Essential | Signature | Luxury |\n|---|---|---|:-:|:-:|:-:|\n`;
  for (const [k, f] of items) md += `| ${f.label} | \`${k}\` | ${f.description} | ${sets.ESSENTIAL.has(k) ? "✓" : ""} | ${sets.SIGNATURE.has(k) ? "✓" : ""} | ${sets.LUXURY.has(k) ? "✓" : ""} |\n`;
  md += "\n";
}
mkdirSync("docs", { recursive: true });
writeFileSync("docs/FEATURES.md", md);
console.log(`docs/FEATURES.md — ${Object.keys(FEATURES).length} entitlements in ${groups.size} groups`);
