/**
 * Metadata for the bundled stock photographs in assets/stock/ — plain-language alt text and a focal point for each.
 *
 * Files are resized from Unsplash originals; the photographer and licence of every picture are in assets/stock/CREDITS.md.
 * They are used in three places and never hot-linked: the demonstration invitations (uploaded through the normal media
 * pipeline), the product site (served resized by /stock/[id]) and the seed scripts.
 *
 * Every picture of a person is a real photograph of a real person used as a STAND-IN for a fictional invitation; the
 * sample invitations say so in their footer.
 */
export interface StockInfo {
  /** Plain-language description (used as alt text). */
  alt: string;
  /** Focal point in percent — keeps faces in frame when the picture is cropped to a screen. */
  focal?: { x: number; y: number };
}

export const STOCK: Record<string, StockInfo> = {
  // north Indian, red & gold
  "2oQy4GAGxbk": { alt: "The bride and groom walking hand in hand along a tree-lined path, he in an ivory and red sherwani, she in a red lehenga", focal: { x: 50, y: 17 } },
  "2XXQkrL0k-Q": { alt: "The couple walking hand in hand towards a palace gateway lined with flowers and candles at dusk", focal: { x: 50, y: 86 } },
  "3ZISmV72cbM": { alt: "A groom in an orange safa touches foreheads with his bride in a golden dupatta", focal: { x: 50, y: 40 } },
  "VPwSJhu5uhs": { alt: "Portrait of the bride in a red veil and gold jewellery, smiling among red roses", focal: { x: 50, y: 38 } },
  "mab4JkLEe80": { alt: "Portrait of the groom in a white sherwani and turban", focal: { x: 50, y: 33 } },
  "7O422yG_b80": { alt: "A couple seated under a floral mandap during the wedding ceremony", focal: { x: 50, y: 55 } },
  "BEdxXAiRfRM": { alt: "A grand ballroom with a flower-covered mandap and glowing chandeliers", focal: { x: 50, y: 55 } },
  "IFCN-tBVNPI": { alt: "The groom during haldi, showered with marigold petals", focal: { x: 50, y: 35 } },
  "SUwPo4ErQCc": { alt: "Two hands decorated with intricate henna holding each other", focal: { x: 50, y: 50 } },
  "gG5MoExhMnU": { alt: "The groom in a golden sherwani laughing with his family during the baraat", focal: { x: 50, y: 40 } },
  "bWQ6-0c_ZcM": { alt: "Hands with henna and bangles joined with a sacred thread during the ceremony", focal: { x: 50, y: 50 } },
  "lAze38kfdAs": { alt: "Hands joined beside the sacred fire during the pheras", focal: { x: 50, y: 40 } },
  "OQDYhr9HRNo": { alt: "The couple under a glowing floral arch as petals fill the sky", focal: { x: 50, y: 50 } },
  "fVL0zZdk-R4": { alt: "Hands clasped, a golden embroidered lehenga beside a sherwani", focal: { x: 50, y: 40 } },
  "EiGfP6DxgN8": { alt: "An offering of betel leaf and flowers held in henna-decorated hands", focal: { x: 50, y: 50 } },
  "d9RsO9BHFVQ": { alt: "The couple posing under a canopy of golden fairy lights", focal: { x: 50, y: 40 } },
  "SHFOaVaVe2A": { alt: "The couple embracing on a forest path in dappled light", focal: { x: 50, y: 55 } },
  "shqK5G-J-Ac": { alt: "The groom in an embroidered sherwani with his bride in a red dupatta", focal: { x: 50, y: 35 } },
  "NCrvRQdvTx8": { alt: "The couple in traditional attire at night, her dupatta draped over his shoulder", focal: { x: 50, y: 40 } },
  "d-jyMeP6uNQ": { alt: "The couple standing on a rock by a river", focal: { x: 50, y: 50 } },
  "8DItNV005qM": { alt: "The bride seated, the groom standing beside her, both wearing flower garlands", focal: { x: 50, y: 45 } },
  "OzyvCE9a60M": { alt: "The couple holding hands, wearing red flower garlands", focal: { x: 50, y: 40 } },
  "kp7XkkCLnlY": { alt: "The bride and groom standing before an ornate floral backdrop", focal: { x: 50, y: 45 } },
  "M8YKi58QKrM": { alt: "The couple exchanging garlands amid scattered red petals", focal: { x: 50, y: 45 } },
  "ohENjR9w0bk": { alt: "The bride in a pink and red veil with gold jewellery, eyes lowered", focal: { x: 50, y: 40 } },
  "2DZmm6QKFQE": { alt: "The bride in a red and gold lehenga standing in an arched doorway", focal: { x: 50, y: 45 } },
  "Po-nggQqplE": { alt: "The bride in a red and gold outfit with henna on her hands", focal: { x: 50, y: 35 } },
  "ICnMRhxJLYg": { alt: "The groom in a golden sherwani and feathered turban", focal: { x: 50, y: 30 } },
  "Y3QEAct9JT4": { alt: "The couple under a canopy of lights, he in a white sherwani, she in red", focal: { x: 50, y: 45 } },
  "jWBxlyVZ3bg": { alt: "The bride and groom side by side at night in embroidered wedding attire", focal: { x: 50, y: 45 } },
  "DC0d6A2kX0k": { alt: "The couple seen from below beneath a ceiling of jasmine strings", focal: { x: 50, y: 50 } },
  "lKwp3-FQomY": { alt: "A bride’s henna-decorated hand held in the groom’s", focal: { x: 50, y: 50 } },
  // Kerala
  "ZghCtT63KMk": { alt: "The couple in kasavu, wearing green garlands, smiling close together at a temple at dusk", focal: { x: 48, y: 54 } },
  "Zx9In5UiU0w": { alt: "The couple laughing together, she holding a lotus, he in a mundu", focal: { x: 55, y: 58 } },
  "b9xLrj7w2AY": { alt: "The couple walking together, garlanded, he in a mundu, she in a red saree", focal: { x: 50, y: 55 } },
  "VJP7K4uihUA": { alt: "A family in cream kasavu embracing the bride at a railway platform", focal: { x: 50, y: 45 } },
  "Rm9DL9DmGi4": { alt: "Portrait of the bride in a gold and red silk saree by the sea", focal: { x: 50, y: 32 } },
  "gXWVyFpRCRU": { alt: "Portrait of the groom in a white sherwani against a green wall", focal: { x: 50, y: 30 } },
  "UX3-_dGbCzk": { alt: "A golden stage under a banyan tree strung with hanging marigold garlands, lit at dusk", focal: { x: 50, y: 70 } },
  "SiMzEeMrX2E": { alt: "A father and his young child wearing flower garlands, touching foreheads", focal: { x: 50, y: 40 } },
  "rjgFxE3eARQ": { alt: "The bride in a pink and gold kanjivaram saree among yellow blossoms", focal: { x: 50, y: 40 } },
  "lj6_-FoCHng": { alt: "The couple beside a vintage car outside an old church", focal: { x: 50, y: 50 } },
  "ykcXm_u84sg": { alt: "The couple exchanging rings amid falling petals", focal: { x: 50, y: 50 } },
  "Xqa_NWl4xEY": { alt: "The bride in a bright saree and gold jewellery between two trees", focal: { x: 50, y: 35 } },
  "0mYmjAkmScE": { alt: "An ornate arched hall with chandeliers, ready for the ceremony", focal: { x: 50, y: 55 } },
  // Christian (church wedding)
  "Iv3yJpmOmZc": { alt: "The bride and groom walking out of the church between guests holding sparklers, smiling", focal: { x: 47, y: 45 } },
  "c9gbbHY_8RU": { alt: "The bride smiling up at her groom, holding a bouquet of cream roses", focal: { x: 49, y: 46 } },
  "SrWVeL5DyNM": { alt: "The couple kneeling at the altar during the wedding service", focal: { x: 50, y: 60 } },
  "zyguVcuzeGM": { alt: "A cathedral aisle dressed with white flowers and tulle", focal: { x: 50, y: 55 } },
  "7enPZgey7vE": { alt: "A red carpet leading down the aisle of a church", focal: { x: 50, y: 55 } },
  "9ceNKX2ZlT0": { alt: "Two wedding rings resting on an open book", focal: { x: 50, y: 50 } },
  "RJDWzHyh6gE": { alt: "The ring is placed on the bride’s finger during the blessing", focal: { x: 50, y: 50 } },
  "ozOQglKbMuE": { alt: "The couple kneeling before the priest during the ceremony", focal: { x: 50, y: 55 } },
  "nKJzYDP10Zw": { alt: "The couple kneeling at the altar as the priest raises the Eucharist", focal: { x: 50, y: 55 } },
  "6bFp65WVrL8": { alt: "Newlyweds showered with petals as they leave the church", focal: { x: 50, y: 45 } },
  "pyd736FSNvk": { alt: "A wedding reception dinner in a grand hall, guests seated at long tables", focal: { x: 50, y: 50 } },
  "coWejNeBFhE": { alt: "The bride and groom at the altar of a church", focal: { x: 50, y: 55 } },
  "fPFoUSKZGts": { alt: "The bride walking down the aisle with her father", focal: { x: 50, y: 50 } },
  "YyvpmN6PB3I": { alt: "A black-and-white view down the aisle as the couple stand at the altar", focal: { x: 50, y: 50 } },
  "6pUz0KMMCX4": { alt: "The bride in a veil beside the groom, flowers glowing in candlelight", focal: { x: 55, y: 40 } },
  "KiU1Du5pONA": { alt: "The couple embracing on a cobbled street beside an old church wall", focal: { x: 80, y: 50 } },
  "q9GlHcaaSn4": { alt: "The couple walking towards an ornate church at dusk", focal: { x: 50, y: 60 } },
  "G5a1RNy55pw": { alt: "A stained-glass window above a chapel overlooking the sea", focal: { x: 50, y: 40 } },
  "GAFpZ63GEYs": { alt: "The groom holding the bride’s hand, her lace gown and bouquet beside him", focal: { x: 50, y: 50 } },
  "h-Q955luWLI": { alt: "A white wedding gown and bouquet in front of the church pews", focal: { x: 50, y: 50 } },
  "QPL_171Kf5Q": { alt: "A white church with tall spires against a deep blue sky", focal: { x: 50, y: 40 } },
  "ouh94xUqOHk": { alt: "A Kerala church with a tall façade and red steps under a blue sky", focal: { x: 50, y: 50 } },
  "YeJWDWeIZho": { alt: "Two gold rings resting on a page that defines marriage", focal: { x: 50, y: 50 } },
  // Muslim (nikah)
  "l6BafhpDlZM": { alt: "The groom in a cream sherwani and the bride in a red and gold lehenga seated together", focal: { x: 50, y: 40 } },
  "1iuFKizvxQo": { alt: "The bride in a hijab and the groom embracing against an old stone wall", focal: { x: 50, y: 32 } },
  "21NahBnXWxI": { alt: "The bride in a green hijab and yellow outfit smiling, henna on her hands", focal: { x: 50, y: 22 } },
  "_fb7LvFNJ4k": { alt: "The groom in a turban kisses the bride’s forehead, she in a red dupatta", focal: { x: 34, y: 22 } },
  "ryOiannoQ3g": { alt: "The nikahnama being signed, henna-decorated hands beside it", focal: { x: 50, y: 50 } },
  "gfVofr15ICc": { alt: "Women showing hands decorated with intricate black henna patterns", focal: { x: 50, y: 50 } },
  "jt2iZ0ARWoY": { alt: "Two rings in a red box resting on the grass", focal: { x: 50, y: 60 } },
  "t8zrGJlSb0M": { alt: "The couple holding hands at the doorway of an old stone building", focal: { x: 50, y: 60 } },
  "464ps_nOflw": { alt: "The couple holding hands, their shadows on the grass", focal: { x: 50, y: 50 } },
  "9Lq0zlOu_dw": { alt: "The newlyweds in white holding their marriage books", focal: { x: 50, y: 45 } },
  "_G7UyLmY1tc": { alt: "The bride in a white gown, veil and jasmine headpiece", focal: { x: 50, y: 25 } },
  "EcERopBq9dg": { alt: "The bride touching the groom’s hand to her forehead in respect", focal: { x: 50, y: 50 } },
  "XYwHswmjjVs": { alt: "The bride in white lace and jasmine, hands together in prayer", focal: { x: 50, y: 30 } },
  "0QL68R5wGRU": { alt: "The bride’s henna-decorated hands pressed together in a quiet prayer", focal: { x: 50, y: 30 } },
  "-4xe-LfXbDs": { alt: "The bride in a red and gold embroidered dupatta, seen in profile", focal: { x: 50, y: 25 } },
  "AGcM0IujgBU": { alt: "The bride in red and gold, her henna-decorated hands at her face", focal: { x: 50, y: 30 } },
  "_tWvgxrO14M": { alt: "The bride in a beaded ivory gown and dupatta at sunset", focal: { x: 50, y: 25 } },
  "Lk4Au3jIqcY": { alt: "The bride in a maroon and gold bridal gown in a hall of chandeliers", focal: { x: 50, y: 25 } },
  "mb-qgRDcz-s": { alt: "The bride lifting a sheer orange and pink veil", focal: { x: 50, y: 30 } },
  "JY0El1DESkw": { alt: "A heart embroidered on the bride’s sleeve", focal: { x: 50, y: 50 } },
  "cRyUjYf6VBQ": { alt: "The couple standing back to back on a hilltop at dusk", focal: { x: 50, y: 45 } },
  "kdYjB1fsyqw": { alt: "The bride in a beige abaya and tiara in prayer with her family", focal: { x: 50, y: 40 } },
  "A--OZVONuGE": { alt: "Gold embroidery on the groom’s sherwani beside the bride’s henna-decorated hand", focal: { x: 50, y: 50 } },
  "2uWUf5K-INY": { alt: "The bride in a white gown and ornate headpiece in a flower-filled hall", focal: { x: 50, y: 35 } },
  "IiGkUvXXbig": { alt: "A smiling bride in white with a bouquet", focal: { x: 50, y: 28 } },
  // ── modern minimal wedding ───────────────────────────────────────────
  "pLDDrRkLMWY": { alt: "Black-and-white close-up of a couple, foreheads together, her hand on his cheek", focal: { x: 50, y: 45 } },
  "aen7e0u2UhA": { alt: "A couple in wedding clothes standing together at the edge of a lake, under a wide cloudy sky", focal: { x: 36, y: 55 } },
  "dYgv-1JnPTA": { alt: "A bride in a lace veil laughing with her groom in golden evening light, a bouquet of blush flowers in her hands", focal: { x: 50, y: 30 } },
  "z96DMIRABU0": { alt: "A bride in a voluminous white gown holding a bouquet beneath a draped white wedding arch", focal: { x: 50, y: 22 } },
  "DnJioJ8nhxI": { alt: "A groom in a black suit adjusting the cuff of his shirt and his watch", focal: { x: 50, y: 50 } },
  "ys_8FnQv6Is": { alt: "A wedding ceremony in a tall timber-and-glass chapel, the bride walking down the aisle between guests", focal: { x: 50, y: 55 } },
  "YKBT8rRAzpU": { alt: "A long wedding table dressed in white linen with a trailing greenery runner and candles", focal: { x: 50, y: 50 } },
  "1cc4TpwK2fE": { alt: "A bride and groom smiling, their noses touching, in a close embrace", focal: { x: 50, y: 50 } },
  "THEJX2MIVPI": { alt: "A couple holding hands, their wedding bands showing, a bouquet of white roses between them", focal: { x: 50, y: 55 } },
  "4ExHGkN7fzQ": { alt: "A bride in a veil holding a loose white-and-green bouquet at her waist", focal: { x: 50, y: 55 } },
  "PzmfTLaqPT0": { alt: "A hand in a pearl-studded glove holding calla lilies tied with white ribbon", focal: { x: 50, y: 45 } },
  "LQoCpIagZmc": { alt: "A white ranunculus and eucalyptus leaves against a deep teal backdrop", focal: { x: 55, y: 45 } },
  "hYkOoi7z9sA": { alt: "A reception table with white hydrangeas, candles, glass bottles and small plates", focal: { x: 50, y: 50 } },
  "J03oQgePJog": { alt: "A bride and groom kiss among applauding guests, a little girl held up to watch", focal: { x: 45, y: 45 } },
  "Jky1XZp--hI": { alt: "A couple standing in the doorway of a canvas glamping tent on a platform in a forest", focal: { x: 50, y: 50 } },
  "Gw2ODMZDeK4": { alt: "Rows of white folding chairs set for a ceremony in a green field, a wooden arch and mountains in the sun-flared distance", focal: { x: 50, y: 40 } },
  "NApm82co2l4": { alt: "A bride in a full ball gown standing on the steps of a triangular chapel, a stained-glass cross glowing behind her at night", focal: { x: 50, y: 60 } },

  // ── thirtieth birthday ───────────────────────────────────────────────
  "aHJ0hciTzG4": { alt: "Portrait of a woman in a black plunging dress with a metallic belt, both hands in her hair, against a dark background", focal: { x: 50, y: 28 } },
  "u2tgn9AA5uY": { alt: "A woman in a black one-shoulder dress seen from behind, holding a glass of wine and watching the sun set over the sea", focal: { x: 35, y: 45 } },
  "UJynGW4gF-I": { alt: "A chocolate cake decorated with ivory sugar roses and candles shaped like the numbers three and zero", focal: { x: 60, y: 35 } },
  "F-q2-0GmtPU": { alt: "A white frosted cake on a stand, crowded with lit candles against soft golden lights", focal: { x: 50, y: 30 } },
  "ETGJjk9o-48": { alt: "A cake covered in lit candles glowing in a dark room", focal: { x: 60, y: 55 } },
  "ch4Fc1cGTq4": { alt: "Hands raising champagne flutes together in a toast in dappled sunlight", focal: { x: 50, y: 40 } },
  "6ciLddToTgM": { alt: "Two glasses of white wine clinking over a restaurant table", focal: { x: 45, y: 55 } },
  "OYIMPsTYVbQ": { alt: "A hand holding a champagne flute in front of a harbour full of moored yachts", focal: { x: 60, y: 45 } },
  "XKCo9N6gyS4": { alt: "A sparkler burning brightly against a deep blue night sky", focal: { x: 50, y: 45 } },
  "vRa4PuRCW18": { alt: "Friends dancing with their arms in the air on a rooftop, a city skyline behind them", focal: { x: 55, y: 40 } },
  "EGDqdOwzGJo": { alt: "A rooftop terrace among glass towers at dusk, the city lights coming on", focal: { x: 40, y: 50 } },
  "PyL-lApI1F8": { alt: "A candle-lit dinner table with flowers, plates and warm strip lighting", focal: { x: 50, y: 50 } },
  "hDzql_ITjmY": { alt: "A restaurant table with dishes to share and a wrapped bouquet beside a small lamp", focal: { x: 50, y: 50 } },
  "csK5XPO87lI": { alt: "A garden pergola with sheer white curtains and string lights glowing at dusk", focal: { x: 50, y: 50 } },
  "H7JlEmkKqW8": { alt: "A laughing woman in a pink dress holding a glass, against a white wall", focal: { x: 35, y: 45 } },

  // ── children's birthday ──────────────────────────────────────────────
  "iG98pmgWJMU": { alt: "Two small children in matching dinosaur birthday T-shirts standing in front of an arch of pastel balloons", focal: { x: 52, y: 55 } },
  "As8zq82LBpw": { alt: "Three children leaning in to blow out the candles on a tall layered cake", focal: { x: 50, y: 38 } },
  "cK6ixOQx1fI": { alt: "A little girl in a paper crown about to blow out the candles on her cake", focal: { x: 55, y: 45 } },
  "Hli3R6LKibo": { alt: "Shiny balloons in green, pink and gold floating against a ceiling", focal: { x: 50, y: 40 } },
  "vrkSVpOwchk": { alt: "A bunch of bright balloons in red, blue and yellow held by one hand", focal: { x: 50, y: 40 } },
  "zURPcpLoKA4": { alt: "A box of cupcakes with pastel frosting and little carrot toppers", focal: { x: 50, y: 50 } },
  "yxZjTv30tl8": { alt: "Three toy dinosaurs in green and orange lined up on a white surface", focal: { x: 50, y: 55 } },
  "PhuGmoubvo8": { alt: "A boy in a white shirt and bow tie blowing soap bubbles", focal: { x: 22, y: 40 } },
  "qojqVPsfAiE": { alt: "A little boy running through a cloud of soap bubbles on the grass", focal: { x: 40, y: 50 } },
  "Wdb27cW27do": { alt: "Children chasing giant soap bubbles in a park", focal: { x: 50, y: 55 } },
  "JatNzrnc078": { alt: "Green plush dinosaur toys hanging over the rail of a toy stall", focal: { x: 50, y: 30 } },

  // ── naming ceremony ──────────────────────────────────────────────────
  "ZzlLBmKFxpA": { alt: "A newborn baby lying in a wicker basket on a blue blanket, looking up", focal: { x: 28, y: 40 } },
  "wDGrvGUWOpE": { alt: "A newborn in a soft cap, wrapped in a striped blanket and smiling in her sleep", focal: { x: 50, y: 35 } },
  "qx7ZQwbgm1c": { alt: "Black-and-white photograph of a sleeping newborn tucked into blankets", focal: { x: 30, y: 40 } },
  "I8Ik4L3lPrs": { alt: "Black-and-white photograph of a baby’s tiny feet cupped in a parent’s hands", focal: { x: 50, y: 45 } },
  "saW6YxGBFkw": { alt: "Black-and-white photograph of a baby’s feet held between two hands in the shape of a heart", focal: { x: 50, y: 65 } },
  "ybvTwLSBtSY": { alt: "A baby’s feet peeking out from under a knitted blanket", focal: { x: 60, y: 70 } },
  "zNY2lVIRh7M": { alt: "Three small oil lamps burning in the dark", focal: { x: 55, y: 65 } },
  "ZLmLOclfeE4": { alt: "Black-and-white photograph of an elder’s hand holding a younger hand wearing bracelets", focal: { x: 50, y: 50 } },
  "y0OAmd_COUM": { alt: "A baby’s hand resting on the weathered hand of a grandparent", focal: { x: 50, y: 60 } },
  "WciKbLIFGxc": { alt: "A steel plate of Indian sweets with marigold, kumkum and a decorated thread beside it", focal: { x: 50, y: 50 } },
  "zx0Xt9u1ekw": { alt: "A baby’s feet held gently in a parent’s hand", focal: { x: 45, y: 55 } },

  // ── engagement ───────────────────────────────────────────────────────
  "AD3k4pko7wo": { alt: "A couple in a close embrace, foreheads touching, lit from behind by a warm golden sun", focal: { x: 45, y: 28 } },
  "1dzXfvALJxs": { alt: "An Indian couple embracing in a eucalyptus grove, she in a blue saree with a red border, he in a navy kurta", focal: { x: 48, y: 45 } },
  "K2JtyCVdeuQ": { alt: "Two joined hands decorated with henna and flower bracelets, the groom in a lavender kurta behind", focal: { x: 50, y: 60 } },
  "OmLrFODvPII": { alt: "A man slipping a gold ring onto his fiancée’s finger", focal: { x: 50, y: 45 } },
  "zy6p2ibONaQ": { alt: "Two hands side by side, each wearing a ring, resting on a white lace dress", focal: { x: 50, y: 45 } },
  "sQcvXmxgPfw": { alt: "A man offering a ring to a woman’s hand in warm, blurred evening light", focal: { x: 55, y: 50 } },
  "TLBDWV7RRYI": { alt: "A couple standing close among autumn leaves, she leaning against him", focal: { x: 50, y: 45 } },
  "QoBHQuiu9N0": { alt: "A couple walking hand in hand across a wide field towards the setting sun", focal: { x: 45, y: 70 } },
  "xXHyI3ZRByo": { alt: "A couple walking through a field of yellow rapeseed flowers", focal: { x: 50, y: 55 } },
  "nBFagEIwy0o": { alt: "Black-and-white photograph of a laughing couple, she hugging him from behind", focal: { x: 50, y: 38 } },
  "WHNWkO1lBKU": { alt: "A couple with foreheads together and hands joined, glowing in golden backlight", focal: { x: 50, y: 35 } },
  "NNNRQgsQXpE": { alt: "A couple standing together beneath a weeping willow in golden light", focal: { x: 45, y: 50 } },
  "IjdzkDxKjc4": { alt: "A couple walking hand in hand through tall dry grass under a pale sky", focal: { x: 50, y: 58 } },

  // ── twenty-fifth anniversary ─────────────────────────────────────────
  "0keyorgl820": { alt: "A silver-haired couple sitting close on a sofa, she resting her head on his shoulder, smiling at the camera", focal: { x: 45, y: 38 } },
  "hZ8bAA8CjcA": { alt: "The same couple on their sofa, holding hands and smiling", focal: { x: 45, y: 38 } },
  "iV9F0sHl7OU": { alt: "A man with glasses and a woman in a pink cardigan sitting side by side, smiling warmly", focal: { x: 50, y: 38 } },
  "vN2V5iunLc0": { alt: "Black-and-white photograph of an older couple walking away hand in hand, he in a sun hat", focal: { x: 50, y: 45 } },
  "M4RvX4uVb4w": { alt: "Black-and-white photograph of a couple dancing close among other dancers", focal: { x: 50, y: 40 } },
  "mrQ6Kmfa1jA": { alt: "A couple dancing tango in a lamp-lit hall", focal: { x: 50, y: 45 } },
  "PPNhNVZal8g": { alt: "A red-haired grandmother dancing happily with a man at a wedding reception", focal: { x: 50, y: 38 } },
  "73OJLcahQHg": { alt: "Hands holding open an old photo album full of black-and-white family pictures", focal: { x: 50, y: 50 } },

  // ── leadership conclave ──────────────────────────────────────────────
  "gofAFBM6Q7Y": { alt: "The vaulted timber ceiling of a concert hall, its curved ribs sweeping down to rows of empty chairs", focal: { x: 50, y: 40 } },
  "bAwT-vSd46Y": { alt: "A city skyline across the water at dusk under a pink and purple sky", focal: { x: 50, y: 70 } },
  "3aVlWP-7bg8": { alt: "An audience seated in rows in a lecture hall, seen from above", focal: { x: 50, y: 50 } },
  "F2KRf_QfCqw": { alt: "An audience seen from behind in a darkened hall with a dotted acoustic wall", focal: { x: 50, y: 60 } },
  "mUUAVJCjwKA": { alt: "A speaker in a black shirt gesturing as he talks from a podium on stage", focal: { x: 65, y: 35 } },
  "u6RJY5F3yM8": { alt: "A woman speaking into a microphone at a lectern on a dark stage", focal: { x: 62, y: 40 } },
  "-U_5mtNdPtA": { alt: "A panel of speakers seated in a row on a stage in front of a deep blue backdrop", focal: { x: 50, y: 55 } },
  "yTsy3PYFPtc": { alt: "Delegates talking over coffee in a bright, open loft-style space", focal: { x: 60, y: 45 } },
  "rjx4A724IuI": { alt: "A small group of men chatting with coffee cups in a modern corridor", focal: { x: 55, y: 40 } },
  "ULh4MH-VxwI": { alt: "A group of colleagues talking in a bright lobby, seen from above", focal: { x: 50, y: 50 } },
  "qPFarjVIR8U": { alt: "Portrait of a smiling man in a bright blue suit, hands clasped, against a dark background", focal: { x: 50, y: 35 } },
  "P5vYhunc6Ac": { alt: "Portrait of a smiling woman with wavy brown hair against a deep navy backdrop", focal: { x: 55, y: 40 } },
  "vZbWlXzZtAY": { alt: "A smiling man in a dark suit and striped tie standing outdoors", focal: { x: 40, y: 40 } },
  "5pZLu6-Y5Xc": { alt: "A smiling woman with long wavy hair and sunglasses on her head, in a dark blazer", focal: { x: 50, y: 35 } },
  "QF21BkDlQHo": { alt: "A young man in a blue striped shirt leaning against a wall, looking at the camera", focal: { x: 45, y: 33 } },
  "H2nJ05_Vf2U": { alt: "Black-and-white photograph of a woman with braided hair accessories speaking into a microphone", focal: { x: 50, y: 30 } },

  // ── technology summit ────────────────────────────────────────────────
  "V-pSsJdyHs4": { alt: "A packed crowd facing a stage lit with blue beams of light", focal: { x: 50, y: 35 } },
  "bzdhc5b3Bxs": { alt: "A presenter on a dark stage beside a giant screen showing an app design, the audience in silhouette", focal: { x: 50, y: 45 } },
  "Tho4zZM8Vhs": { alt: "People working on laptops side by side in a café-style workspace", focal: { x: 50, y: 55 } },
  "Y4uoL2SIGUQ": { alt: "A team meeting around a long table in an open-plan office", focal: { x: 50, y: 45 } },
  "ixKxQE29Mn0": { alt: "A presenter in a blue blazer holding a microphone beside a slide that asks how to apply data to business decisions", focal: { x: 68, y: 55 } },
  "LMWaGpIyOTs": { alt: "A smiling man in a navy double-breasted suit gesturing as he speaks, outdoors", focal: { x: 50, y: 25 } },
  "7TI-3jUObYg": { alt: "A smiling man in a bright blue suit and purple tie standing in a sunlit park", focal: { x: 55, y: 30 } },
  "5gZDLuXQo-M": { alt: "A man in a blue three-piece suit with a lapel microphone, smiling", focal: { x: 50, y: 28 } },
  "a0EQFTH4ZfA": { alt: "A woman in a grey blazer looking over her shoulder, city towers behind her", focal: { x: 50, y: 30 } },
  "9iLbXsMZ6ls": { alt: "A laughing woman with curly blonde hair in a beige trench coat", focal: { x: 50, y: 30 } },
  "2QDYXAEfFPk": { alt: "A smiling woman with long dark hair against a teal dusk sky", focal: { x: 50, y: 38 } },
  "2K1CdpU5ABo": { alt: "Two men smiling as they work at laptops side by side", focal: { x: 50, y: 45 } },
  "XZkk5xT8Xrk": { alt: "Developers working at tables in a dimly lit room with exposed brick walls", focal: { x: 50, y: 50 } },

  // ── memorial ─────────────────────────────────────────────────────────
  "tjIrHQzYIVE": { alt: "Portrait of an elderly man with a white beard and white hair, looking calmly at the camera", focal: { x: 50, y: 38 } },
  "J3H-rth8cck": { alt: "A single white candle burning in a dark candlestick", focal: { x: 50, y: 50 } },
  "GAscwTkEOy8": { alt: "Rows of candles glowing softly, their lights blurred into gold", focal: { x: 50, y: 40 } },
  "df6Z3DPPw5U": { alt: "A single oil lamp burning in the dark", focal: { x: 70, y: 62 } },
  "B5AmTy1K6mk": { alt: "Close-up of a candle flame glowing amber", focal: { x: 50, y: 45 } },
  "R1H2Y7T7m3I": { alt: "An elderly person’s hands resting on a window ledge, a wedding ring on one finger", focal: { x: 60, y: 55 } },
  "aauHMskRPa8": { alt: "White lilies against a pale, cloudless sky", focal: { x: 50, y: 40 } },
  "4nN6aN45y7c": { alt: "White lilies in a glass vase against a warm golden background", focal: { x: 50, y: 45 } },
  "FPVzkHF3wgM": { alt: "The sun setting over a calm sea, light on the waves", focal: { x: 50, y: 55 } },
  "R9tPheZuGnA": { alt: "Rays of sunlight falling across a quiet path through a forest", focal: { x: 50, y: 50 } },
  "UpNwL3hTcRg": { alt: "A wooden boardwalk leading through misty pine trees at sunrise", focal: { x: 50, y: 55 } },
  "3pW91fGAKiE": { alt: "A misty valley of dark forest under a pink dawn sky", focal: { x: 50, y: 50 } },
  "yJFk7YwxDbA": { alt: "A pair of reading glasses resting on an open book on white linen", focal: { x: 50, y: 45 } },
  "heNLI144X7Y": { alt: "Open books scattered across a table with reading glasses and a small plant", focal: { x: 50, y: 50 } },
  "4KkTFccuZ0M": { alt: "A rose garden with a white pergola and benches in warm light", focal: { x: 50, y: 55 } },
};

export function stockInfo(id: string): StockInfo | undefined {
  return Object.prototype.hasOwnProperty.call(STOCK, id) ? STOCK[id] : undefined;
}

/** A stock id is letters, digits, "-" and "_" only — the file name of a photograph in assets/stock/. */
export const STOCK_ID = /^[A-Za-z0-9_-]{6,24}$/;
